version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ${WORKSPACE_PATH}/postgre:/workspace
    restart: "no"
volumes:
  pgdata:
